// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateDatabaseUsingSSHRequest struct {
	Referer     *string `header:"style=simple,explode=false,name=Referer"`
	RequestBody *string `request:"mediaType=*/*"`
}

func (o *CreateDatabaseUsingSSHRequest) GetReferer() *string {
	if o == nil {
		return nil
	}
	return o.Referer
}

func (o *CreateDatabaseUsingSSHRequest) GetRequestBody() *string {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type CreateDatabaseUsingSSHResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *CreateDatabaseUsingSSHResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateDatabaseUsingSSHResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateDatabaseUsingSSHResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
