// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAPIV1AnnotationLayerAnnotationLayerIDRequest struct {
	AnnotationLayerID string  `pathParam:"style=simple,explode=false,name=AnnotationLayerID"`
	Referer           *string `header:"style=simple,explode=false,name=Referer"`
}

func (o *DeleteAPIV1AnnotationLayerAnnotationLayerIDRequest) GetAnnotationLayerID() string {
	if o == nil {
		return ""
	}
	return o.AnnotationLayerID
}

func (o *DeleteAPIV1AnnotationLayerAnnotationLayerIDRequest) GetReferer() *string {
	if o == nil {
		return nil
	}
	return o.Referer
}

type DeleteAPIV1AnnotationLayerAnnotationLayerIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *DeleteAPIV1AnnotationLayerAnnotationLayerIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteAPIV1AnnotationLayerAnnotationLayerIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteAPIV1AnnotationLayerAnnotationLayerIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
