// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1DashboardDashboardIDChartsRequest struct {
	DashboardID string `pathParam:"style=simple,explode=false,name=DashboardID"`
}

func (o *GetAPIV1DashboardDashboardIDChartsRequest) GetDashboardID() string {
	if o == nil {
		return ""
	}
	return o.DashboardID
}

type GetAPIV1DashboardDashboardIDChartsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *GetAPIV1DashboardDashboardIDChartsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPIV1DashboardDashboardIDChartsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPIV1DashboardDashboardIDChartsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
