// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1DashboardExportRequest struct {
	// Comma separated list of Dashboard IDs.
	Q *string `queryParam:"style=form,explode=true,name=q"`
}

func (o *GetAPIV1DashboardExportRequest) GetQ() *string {
	if o == nil {
		return nil
	}
	return o.Q
}

type GetAPIV1DashboardExportResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *GetAPIV1DashboardExportResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPIV1DashboardExportResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPIV1DashboardExportResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
