// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1DatasetExportRequest struct {
	// Comma separated list of Dataset IDs.
	Q *string `queryParam:"style=form,explode=true,name=q"`
}

func (o *GetAPIV1DatasetExportRequest) GetQ() *string {
	if o == nil {
		return nil
	}
	return o.Q
}

type GetAPIV1DatasetExportResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *GetAPIV1DatasetExportResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPIV1DatasetExportResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPIV1DatasetExportResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
