// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDRequest struct {
	AnnotationID      string  `pathParam:"style=simple,explode=false,name=AnnotationID"`
	AnnotationLayerID string  `pathParam:"style=simple,explode=false,name=AnnotationLayerID"`
	Referer           *string `header:"style=simple,explode=false,name=Referer"`
}

func (o *GetAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDRequest) GetAnnotationID() string {
	if o == nil {
		return ""
	}
	return o.AnnotationID
}

func (o *GetAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDRequest) GetAnnotationLayerID() string {
	if o == nil {
		return ""
	}
	return o.AnnotationLayerID
}

func (o *GetAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDRequest) GetReferer() *string {
	if o == nil {
		return nil
	}
	return o.Referer
}

type GetAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *GetAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
