// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1ChartChartIDRequest struct {
	ChartID string `pathParam:"style=simple,explode=false,name=ChartID"`
}

func (o *GetAPIV1ChartChartIDRequest) GetChartID() string {
	if o == nil {
		return ""
	}
	return o.ChartID
}

type GetAPIV1ChartChartIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *GetAPIV1ChartChartIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPIV1ChartChartIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPIV1ChartChartIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
