// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostV1TeamsTeamSlugInvitesRequestBody struct {
}

type PostV1TeamsTeamSlugInvitesRequest struct {
	RequestBody *PostV1TeamsTeamSlugInvitesRequestBody `request:"mediaType=application/json"`
	TeamSlug    string                                 `pathParam:"style=simple,explode=false,name=TeamSlug"`
}

func (o *PostV1TeamsTeamSlugInvitesRequest) GetRequestBody() *PostV1TeamsTeamSlugInvitesRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *PostV1TeamsTeamSlugInvitesRequest) GetTeamSlug() string {
	if o == nil {
		return ""
	}
	return o.TeamSlug
}

type PostV1TeamsTeamSlugInvitesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *PostV1TeamsTeamSlugInvitesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostV1TeamsTeamSlugInvitesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostV1TeamsTeamSlugInvitesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
