// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutAPIV1DatasetDatasetIDRequestBody struct {
}

type PutAPIV1DatasetDatasetIDRequest struct {
	DatasetID   string                               `pathParam:"style=simple,explode=false,name=DatasetID"`
	Referer     *string                              `header:"style=simple,explode=false,name=Referer"`
	RequestBody *PutAPIV1DatasetDatasetIDRequestBody `request:"mediaType=application/json"`
}

func (o *PutAPIV1DatasetDatasetIDRequest) GetDatasetID() string {
	if o == nil {
		return ""
	}
	return o.DatasetID
}

func (o *PutAPIV1DatasetDatasetIDRequest) GetReferer() *string {
	if o == nil {
		return nil
	}
	return o.Referer
}

func (o *PutAPIV1DatasetDatasetIDRequest) GetRequestBody() *PutAPIV1DatasetDatasetIDRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type PutAPIV1DatasetDatasetIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *PutAPIV1DatasetDatasetIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutAPIV1DatasetDatasetIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutAPIV1DatasetDatasetIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
